### ISSUE TITLE
Bike Trail Conditions Notifier

### ISSUE THREAD

**Issue by s1037989** [KeystoneIT/keystoneit.github.io#38]
# Problem

Everyday the parking lots of Greensfelder have several cars with bike racks parked.  So I should have known when I got there and no one else was there that the trails weren't in great shape (due to recent weather).  Well, I ignored my intuition and carried on.  The trails weren't bad, but they were wet, soft, and sloppy.  It kind me to thinking...  Is there a way to communicate trail conditions to everyone... _automatically_??
# Proposal

Taking yet another page from Google, we could use the data made available through Strava (_the_ source of data for everything biking) and create a short-term heatmap.  Google Traffic is very similar to a heatmap.  Let's take the data from Strava and determine the likelihood of good trail conditions.  This way, everyone would just do what they always do and record their data and send it to Strava for processing, and from that we can announce to the world the likelihood of good trail conditions.  Right now, a very common approach is to call your bike shop and ask, ask a friend, or "more sophisticated" approaches have an adjustable conditions sign at the trailhead and people can adjust it and then take a picture of it and hashtag it on twitter.  Nice idea, but that requires a lot of special focus by people.  Can't we just ride and communicate this information automatically??

I'm thinking that every trail would get it's own twitter hashtag or RSS feed and people can subscribe to whichever ones they want.  Any time the trail conditions change, a tweet it sent.  Or, perhaps you just send a tweet to your trail hashtag or email address and get back conditions.  Or perhaps it's a website.  Or perhaps there's a phone app that stores your favorite trails and you can browse current conditions of each.

I'm sure there's a dozen ways that we can communicate the information.  The hard part is determining a somewhat reliable algorithm for determining trail conditions based on Strava trail use data.

It figures: this is _not_ a new [idea](http://www.singletracks.com/blog/mtb-trails/using-data-to-predict-mountain-bike-trail-conditions-and-improve-trails/) [idea](http://www.singletracks.com/blog/mtb-trails/introducing-tracker-automatically-check-in-and-share-your-mtb-rides-on-singletracks/).  There doesn't look to be an implementation -- maybe [TrailForks](http://www.trailforks.com/)?

In the end, there has to be a rapid way to find out -- twitter style, y'know.  We don't want to have to open op a desktop computer and browse around and stuff.

**Comment by ehumes** [comment]
How about looking at the weather data from the previous 48 hours?

**Comment by s1037989** [comment]
That doesn't help me.  Maybe I'm alone, maybe I'm the only guy that doesn't know how to understand the relation between weather and trails, but it unfortunately doesn't help me.  But, really, that's exactly right!  That's exactly what I was thinking as I was biking...  how is it that everyone else knows that the trail conditions are poor and not to show up?

The weather has been really good the past 48 hours, and longer!  The situation, likely, is that the weather got so good that it thawed all the frozen grounds and turned them to mush.  I don't understand that stuff.  But if I just looked at the weather from the past 48 hours (in a sense I did -- weather has been great) I would have gone expecting to have a good ride (I did go and I didn't have  :)

And then there's this...  Literally the day after the massive Eureka flooding, tons of people went and rode trails, even Bluff Trail off of Al Foster.  I asked them if they were nuts!  They said the trails were great.  How'd they know they'd be able to ride those trails??  I wouldn't have thought I could go for 3 weeks after heavy rides like that.

**Comment by AdamSloggett** [comment]
This works with concerned citizens and the police with speed traps. I'm sure having trails and some social aspects would increase the communications... K

**Comment by ehumes** [comment]
Or just use this: http://gorctrails.com/trails

**Comment by AdamSloggett** [comment]
Or that...

**Comment by s1037989** [comment]
Thanks!  Closed.

**Comment by mowgli29** [comment]
Wait, what?! You've never seen that?! I thought you were trying to improve on it. :) Often times, it doesn't get updated enough to matter. :(

Something that would be awesome: you can ask for trail conditions before you go ride and people who've ridden there recently get notified of your request!

**Comment by s1037989** [comment]
Twin Springs has a slick [indicator board](https://scontent-ord1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/12631338_916857341725012_5025466790537792052_n.jpg?oh=c414d2d7d1f8ffe40cfdf8295cf86e95&oe=573D79DB) for you to take a picture and post which is really cool, but still too manual.  It'd be great if Strava data could predict trail conditions automatically.

And yes, I've seen gorc's conditions site before and yes I want to improve on it.

The trail conditions messenger is a really nice idea!  Very social.
