### ISSUE TITLE
Typing is hard: tab completion for email.

### ISSUE THREAD

**Issue by mowgli29** [KeystoneIT/keystoneit.github.io#48]
# Problem

Sometimes, when I type an email, I hit tab to complete the word I'm typing. Naturally, this does nothing.  :) Were I navigating the CLI of a firewall or a *nix machine, it would. 

The key difference is that in the latter scenarios, tab completion operates on the principal that there is only one word you might be trying to spell. With email, the possibilities are endless, so it would need to be an intelligent and adaptive solution.
# Proposal

Develop something, such as a Lab for Gmail, that provides this functionality. Ideally, it would be able to recognize how frequently you use each word, along with context and other factors, and weight its guesses accordingly.

Rob pointed out that phones seem to do this, or something similar, with their autocorrect functionality. How? Can we tap into that technology?

**Comment by AdamSloggett** [comment]
http://www.phraseexpress.com/ has similar functionality... it's actually very useful for repetitive typing like +1 or #cashMoney

**Comment by s1037989** [comment]
That's a super cool problem / proposal!  Good thinking and thanks for posting it here!

PhraseExpress sounds pretty solid -- do you use it, @AdamSloggett?
@mowgli29, how does Adam's suggestion meet your requirements?

What do you guys think about a Gmail Lab for this versus an installed application such as PhraseExpress?  Pros / Cons?

**Comment by AdamSloggett** [comment]
I do use it, probably not as much as I should but it's pretty solid. It's can be tweaked and configured for custom saying and code...

**Comment by codykniffen** [comment]
@mowgli29 This won't solve all of your problems but have you looked in to OS X's built in text expansion? You can roll your own for commonly used text snippets. 

http://www.laptopmag.com/articles/autocomplete-with-text-shortcuts-os-x

**Comment by s1037989** [comment]
From today's meeting:

Gmail plugin that works for Gmail only, Browser extension that works for Browser only, or OS app that works for all apps?  There's certainly problems with making it too broad.  In the end, Josh is just looking for this feature in gmail -- at least for Josh, a gmail plugin might be ideal.

If he feels like it, he'll pull up some ["Hello World" examples](https://developers.google.com/gmail/contextual_gadgets) just to see what it's like building a Gmail plugin.

Tasks
- Create a sample hellow world google gadget app
- Store the project in a new github project in KeystoneIT and link to it here
